import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { apiFetchServer } from '@/lib/api/server'
import AdReportContent from '@/components/public/AdReportContent'

interface Params {
  params: Promise<{ token: string }>
  searchParams: Promise<{
    range?: string
    month?: string
  }>
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { token } = await params

  let campaign: { name: string } | null = null
  try {
    campaign = await apiFetchServer<{ name: string }>(
      `/public/ads/campaigns/by-token/${token}`
    )
  } catch {
    campaign = null
  }

  if (!campaign) return { title: 'Report Not Found' }
  return {
    title: `${campaign.name} | Campaign Report`,
    robots: { index: false, follow: false },
  }
}

export default async function AdReportPage({ params, searchParams }: Params) {
  const { token } = await params
  const { range = '30d', month } = await searchParams
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000'

  const apiUrl = new URL(`${baseUrl}/api/ads/report/${token}`)
  apiUrl.searchParams.set('range', range)
  if (month) apiUrl.searchParams.set('month', month)

  const res = await fetch(apiUrl.toString(), {
    next: { revalidate: 60 } // Revalidate every minute
  })

  if (!res.ok) notFound()
  const stats = await res.json()

  return (
    <div className="min-h-screen bg-zinc-950 text-white selection:bg-indigo-500/30 font-sans antialiased">
      {/* Background Glow */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-[20%] -left-[10%] w-[60%] h-[60%] bg-indigo-900/10 blur-[120px] rounded-full" />
        <div className="absolute top-[10%] -right-[10%] w-[40%] h-[40%] bg-emerald-900/5 blur-[120px] rounded-full" />
      </div>

      <div className="relative max-w-7xl mx-auto px-6 py-16 space-y-16">
        {/* Header */}
        <header className="flex flex-col md:flex-row md:items-end justify-between gap-8 pb-12 border-b border-zinc-900">
          <div className="space-y-6 max-w-2xl">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-br from-indigo-600 to-indigo-800 rounded-xl flex items-center justify-center font-black text-xs shadow-lg shadow-indigo-500/20">P</div>
              <div className="flex flex-col">
                <span className="text-[10px] font-black uppercase tracking-[0.3em] text-indigo-500">Analytics Report</span>
                <span className="text-xs font-bold text-zinc-500">Generated by Creatopedia</span>
              </div>
            </div>

            <div className="space-y-2">
              <h1 className="text-5xl font-black tracking-tighter leading-none bg-clip-text text-transparent bg-gradient-to-b from-white to-zinc-500">
                {stats.campaign_name}
              </h1>
              <div className="flex flex-wrap items-center gap-3 text-sm font-bold">
                <span className="px-3 py-1 bg-zinc-900 border border-zinc-800 rounded-full text-zinc-400">
                  {stats.client_name || 'Direct Advertiser'}
                </span>
                <span className="text-zinc-700">•</span>
                <span className="text-zinc-500">
                  {new Date(stats.starts_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                  {stats.ends_at ? ` — ${new Date(stats.ends_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}` : ' (Ongoing)'}
                </span>
                <span className="text-zinc-700">•</span>
                <span className={`flex items-center gap-2 ${stats.campaign_status === 'active' ? 'text-emerald-400' : 'text-zinc-400'}`}>
                  <div className={`w-1.5 h-1.5 rounded-full ${stats.campaign_status === 'active' ? 'bg-emerald-400 animate-pulse' : 'bg-zinc-600'}`} />
                  {stats.campaign_status.toUpperCase()}
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className="bg-zinc-900/50 border border-zinc-800 p-4 rounded-2xl backdrop-blur-md">
              <div className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest mb-1">Status</div>
              <div className="text-sm font-black text-white">Verified Campaign</div>
            </div>
            <div className="bg-zinc-900/50 border border-zinc-800 p-4 rounded-2xl backdrop-blur-md">
              <div className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest mb-1">Period</div>
              <div className="text-sm font-black text-white text-right">Last 30 Days</div>
            </div>
          </div>
        </header>

        {/* Dynamic Content */}
        <AdReportContent stats={stats} />

        {/* Footer */}
        <footer className="pt-24 pb-12 border-t border-zinc-900">
          <div className="flex flex-col md:flex-row items-center justify-between gap-8 opacity-50 transition-opacity hover:opacity-100">
            <div className="flex items-center gap-4">
              <div className="w-8 h-8 bg-zinc-900 rounded-lg flex items-center justify-center font-bold text-[10px] text-zinc-600 border border-zinc-800">PH</div>
              <div className="text-xs font-bold text-zinc-500">
                © {new Date().getFullYear()} Creatopedia. Internal Ad Analytics Engine.
              </div>
            </div>
            <div className="flex items-center gap-6 text-xs font-bold text-zinc-600">
              <span className="flex items-center gap-2"><div className="w-1 h-1 rounded-full bg-emerald-500" /> Live Data</span>
              <span>•</span>
              <span>Encrypted Report</span>
              <span>•</span>
              <span className="text-zinc-500">Ref: {token.slice(0, 8)}</span>
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}
