"""add subdomain visits table

Revision ID: 6cfd4fe54cfc
Revises: 534075454c35
Create Date: 2026-06-04 09:53:09.022351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cfd4fe54cfc'
down_revision: Union[str, Sequence[str], None] = '534075454c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdomain_visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdomain_visits_creator_id'), 'subdomain_visits', ['creator_id'], unique=False)
    op.create_index(op.f('ix_subdomain_visits_id'), 'subdomain_visits', ['id'], unique=False)
    op.create_index(op.f('ix_subdomain_visits_ip_hash'), 'subdomain_visits', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_subdomain_visits_subdomain'), 'subdomain_visits', ['subdomain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subdomain_visits_subdomain'), table_name='subdomain_visits')
    op.drop_index(op.f('ix_subdomain_visits_ip_hash'), table_name='subdomain_visits')
    op.drop_index(op.f('ix_subdomain_visits_id'), table_name='subdomain_visits')
    op.drop_index(op.f('ix_subdomain_visits_creator_id'), table_name='subdomain_visits')
    op.drop_table('subdomain_visits')
    # ### end Alembic commands ###
