"""initial_schema

Revision ID: badfa881bc8b
Revises: 
Create Date: 2026-05-15 15:28:38.010655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'badfa881bc8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('creators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_tier', sa.Enum('free', 'pro', 'agency', name='plantier'), nullable=False),
    sa.Column('stripe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_email'), 'creators', ['email'], unique=True)
    op.create_index(op.f('ix_creators_handle'), 'creators', ['handle'], unique=True)
    op.create_index(op.f('ix_creators_id'), 'creators', ['id'], unique=False)
    op.create_index(op.f('ix_creators_subdomain'), 'creators', ['subdomain'], unique=True)
    op.create_table('ad_clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='adstatus'), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('report_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_clients_creator_id'), 'ad_clients', ['creator_id'], unique=False)
    op.create_index(op.f('ix_ad_clients_id'), 'ad_clients', ['id'], unique=False)
    op.create_index(op.f('ix_ad_clients_report_token'), 'ad_clients', ['report_token'], unique=True)
    op.create_table('aggregated_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('prompt_views', sa.Integer(), nullable=False),
    sa.Column('prompt_copies', sa.Integer(), nullable=False),
    sa.Column('ad_impressions', sa.Integer(), nullable=False),
    sa.Column('ad_clicks', sa.Integer(), nullable=False),
    sa.Column('email_captures', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_stats_creator_id'), 'aggregated_stats', ['creator_id'], unique=False)
    op.create_index(op.f('ix_aggregated_stats_id'), 'aggregated_stats', ['id'], unique=False)
    op.create_index(op.f('ix_aggregated_stats_stat_date'), 'aggregated_stats', ['stat_date'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.Enum('view', 'click', 'copy', 'email_capture', 'ad_impression', 'ad_click', name='eventtype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_creator_id'), 'event_logs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_event_logs_entity_id'), 'event_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('new', 'read', 'replied', 'archived', name='inquirystatus'), nullable=False),
    sa.Column('read_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('replied_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_creator_id'), 'inquiries', ['creator_id'], unique=False)
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    op.create_table('instagram_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instagram_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_tokens_creator_id'), 'instagram_tokens', ['creator_id'], unique=True)
    op.create_index(op.f('ix_instagram_tokens_id'), 'instagram_tokens', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seo_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seo_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('theme_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id'),
    sa.UniqueConstraint('custom_domain')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_slug'), 'portfolios', ['slug'], unique=True)
    op.create_table('prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sa.Enum('text', 'pdf', name='contenttype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('ai_tool', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_type', sa.Enum('text', 'image', 'video', 'audio', 'code', name='outputtype'), nullable=False),
    sa.Column('gate_type', sa.Enum('open', 'email', 'paid', name='gatetype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='promptstatus'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('copy_count', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_category_id'), 'prompts', ['category_id'], unique=False)
    op.create_index(op.f('ix_prompts_creator_id'), 'prompts', ['creator_id'], unique=False)
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_index(op.f('ix_prompts_slug'), 'prompts', ['slug'], unique=False)
    op.create_table('ad_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='adstatus'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('impression_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['ad_clients.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_client_id'), 'ad_campaigns', ['client_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_creator_id'), 'ad_campaigns', ['creator_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_id'), 'ad_campaigns', ['id'], unique=False)
    op.create_table('email_captures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_captures_email'), 'email_captures', ['email'], unique=False)
    op.create_index(op.f('ix_email_captures_id'), 'email_captures', ['id'], unique=False)
    op.create_index(op.f('ix_email_captures_prompt_id'), 'email_captures', ['prompt_id'], unique=False)
    op.create_table('portfolio_heroes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subheadline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cta_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cta_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('background_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_portfolio_heroes_id'), 'portfolio_heroes', ['id'], unique=False)
    op.create_table('portfolio_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_stats_id'), 'portfolio_stats', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_stats_portfolio_id'), 'portfolio_stats', ['portfolio_id'], unique=False)
    op.create_table('portfolio_works',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_works_id'), 'portfolio_works', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_works_portfolio_id'), 'portfolio_works', ['portfolio_id'], unique=False)
    op.create_table('ad_placements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_type', sa.Enum('discovery', 'prompt', 'category', 'portfolio', 'global_', name='pagetype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_placements_category_id'), 'ad_placements', ['category_id'], unique=False)
    op.create_index(op.f('ix_ad_placements_id'), 'ad_placements', ['id'], unique=False)
    op.create_index(op.f('ix_ad_placements_prompt_id'), 'ad_placements', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_placements_prompt_id'), table_name='ad_placements')
    op.drop_index(op.f('ix_ad_placements_id'), table_name='ad_placements')
    op.drop_index(op.f('ix_ad_placements_category_id'), table_name='ad_placements')
    op.drop_table('ad_placements')
    op.drop_index(op.f('ix_portfolio_works_portfolio_id'), table_name='portfolio_works')
    op.drop_index(op.f('ix_portfolio_works_id'), table_name='portfolio_works')
    op.drop_table('portfolio_works')
    op.drop_index(op.f('ix_portfolio_stats_portfolio_id'), table_name='portfolio_stats')
    op.drop_index(op.f('ix_portfolio_stats_id'), table_name='portfolio_stats')
    op.drop_table('portfolio_stats')
    op.drop_index(op.f('ix_portfolio_heroes_id'), table_name='portfolio_heroes')
    op.drop_table('portfolio_heroes')
    op.drop_index(op.f('ix_email_captures_prompt_id'), table_name='email_captures')
    op.drop_index(op.f('ix_email_captures_id'), table_name='email_captures')
    op.drop_index(op.f('ix_email_captures_email'), table_name='email_captures')
    op.drop_table('email_captures')
    op.drop_index(op.f('ix_ad_campaigns_id'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_creator_id'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_client_id'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    op.drop_index(op.f('ix_prompts_slug'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_creator_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_category_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_portfolios_slug'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_instagram_tokens_id'), table_name='instagram_tokens')
    op.drop_index(op.f('ix_instagram_tokens_creator_id'), table_name='instagram_tokens')
    op.drop_table('instagram_tokens')
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_creator_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_creator_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_aggregated_stats_stat_date'), table_name='aggregated_stats')
    op.drop_index(op.f('ix_aggregated_stats_id'), table_name='aggregated_stats')
    op.drop_index(op.f('ix_aggregated_stats_creator_id'), table_name='aggregated_stats')
    op.drop_table('aggregated_stats')
    op.drop_index(op.f('ix_ad_clients_report_token'), table_name='ad_clients')
    op.drop_index(op.f('ix_ad_clients_id'), table_name='ad_clients')
    op.drop_index(op.f('ix_ad_clients_creator_id'), table_name='ad_clients')
    op.drop_table('ad_clients')
    op.drop_index(op.f('ix_creators_subdomain'), table_name='creators')
    op.drop_index(op.f('ix_creators_id'), table_name='creators')
    op.drop_index(op.f('ix_creators_handle'), table_name='creators')
    op.drop_index(op.f('ix_creators_email'), table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
